id = "peter"
name = "Peter"
description = "A dark theme for Zed"
version = "0.1.0"
schema_version = 1
authors = ["Peter Bassi <https://github.com/peterjbassi>"]
repository = "https://github.com/peterjbassi/peter-zed-theme"

themes = ["themes/peter.json"]
